apiVersion: v1
kind: Service
metadata:
  name: sshd
spec:
  type: LoadBalancer
  selector:
    app: sshd
  ports:
  - protocol: TCP
    port: 22
    targetPort: 22
    nodePort: 30022
---
apiVersion: v1
kind: Service
metadata:
  name: ssh-tunnel
spec:
  selector:
    app: sshd
  ports:
  - protocol: TCP
    port: 6443
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: sshd
  name: sshd
spec:
  selector:
    matchLabels:
      app: sshd
  template:
    metadata:
      labels:
        app: sshd
    spec:
      containers:
      - name: sshd
        image: quay.io/skeeey/sshd:v0.1.0
        imagePullPolicy: IfNotPresent
        command:
        - "/usr/sbin/sshd"
        - "-D"
        ports:
        - containerPort: 22
        - containerPort: 6443

